# Generated by Django 5.2.8 on 2025-11-06 16:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título descriptivo del proyecto",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripción detallada del proyecto",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "documento",
                    models.FileField(
                        help_text="Archivo del proyecto (PDF, DOC, DOCX)",
                        upload_to="proyectos/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx"]
                            )
                        ],
                        verbose_name="Documento",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("enviado", "Enviado"),
                            ("revision", "En Revisión"),
                            ("aprobado", "Aprobado"),
                        ],
                        default="enviado",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Envío"
                    ),
                ),
                (
                    "fecha_revision",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de la última revisión",
                        null=True,
                        verbose_name="Fecha de Revisión",
                    ),
                ),
                (
                    "calificacion",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calificación del proyecto (0.0 - 5.0)",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                        verbose_name="Calificación",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "Estudiante"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proyectos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
                "ordering": ["-fecha_envio"],
                "indexes": [
                    models.Index(
                        fields=["estado", "-fecha_envio"],
                        name="projects_ga_estado_1275a9_idx",
                    ),
                    models.Index(
                        fields=["estudiante", "-fecha_envio"],
                        name="projects_ga_estudia_36abd2_idx",
                    ),
                ],
            },
        ),
    ]
